spring:
  application:
    name: YANP
  datasource:
    url: 'jdbc:mariadb://localhost:3310/'
    username: root
    password: 123456
auth:
  port: 37244
io:
  netty:
    leakDetection:
      level: advanced
server:
  port: 8081